name: Nightly Build

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_t-displays3:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install git make python3 python3-pip cmake quilt
    - name: Build T-DisplayS3
      run: |
        cp config_T-DisplayS3 config
        make
    - name: Deliver firmware
      uses: actions/upload-artifact@v3
      with:
        name: LILYGO_T-DisplayS3_firmware
        path: ./bin/esp32s3/LILYGO_T-DisplayS3/

